# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
ADD . /usr/src/app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir .

# Make port 80 available to the world outside this container
EXPOSE 80

# Run mcp-simple-timeserver when the container launches
ENTRYPOINT ["mcp-simple-timeserver"]