[project]
name = "mcp_simple_timeserver"
version = "1.0.2"
dynamic = ["authors", "dependencies", "readme", "requires-python", "scripts"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
